# -*- coding: utf-8 -*-
"""wuxia_quests.py - Quest system"""

MAIN_QUESTS = [{'id': 'main_001', 'name': '初入江湖', 'desc': '少侠初入江湖，在平安镇安顿下来', 'level_req': 1, 'objectives': [{'type': 'talk', 'target': '老拳师', 'desc': '与老拳师交谈', 'count': 1}, {'type': 'visit', 'target': '龙门客栈', 'desc': '前往龙门客栈', 'count': 1}], 'rewards': {'silver': 50, 'gold': 100, 'xp': 60}, 'next': 'main_002'}, {'id': 'main_002', 'name': '江湖第一战', 'desc': '在擂台上扬名立万', 'level_req': 3, 'objectives': [{'type': 'visit', 'target': '擂台', 'desc': '前往擂台', 'count': 1}, {'type': 'practice', 'desc': '练习武功', 'count': 3}], 'rewards': {'silver': 100, 'gold': 200, 'xp': 120}, 'next': 'main_003'}, {'id': 'main_003', 'name': '襄阳危机', 'desc': '蒙古大军压境，郭靖招募义士', 'level_req': 8, 'objectives': [{'type': 'visit', 'target': '襄阳城', 'desc': '前往襄阳城', 'count': 1}, {'type': 'talk', 'target': '郭靖', 'desc': '与郭靖交谈', 'count': 1}, {'type': 'talk', 'target': '黄蓉', 'desc': '与黄蓉交谈', 'count': 1}], 'rewards': {'silver': 200, 'gold': 500, 'xp': 300}, 'next': 'main_004'}, {'id': 'main_004', 'name': '少室山英雄会', 'desc': '乔峰邀请天下英雄齐聚', 'level_req': 15, 'objectives': [{'type': 'visit', 'target': '龙门客栈', 'desc': '前往龙门客栈', 'count': 1}, {'type': 'talk', 'target': '乔峰', 'desc': '与乔峰交谈', 'count': 1}], 'rewards': {'silver': 500, 'gold': 1000, 'xp': 600}, 'next': None}]

SIDE_QUESTS = [{'id': 'side_001', 'name': '铁匠的请求', 'desc': '铁匠张伯需要好铁矿', 'level_req': 2, 'objectives': [{'type': 'talk', 'target': '铁匠张伯', 'desc': '与铁匠张伯交谈', 'count': 1}, {'type': 'visit', 'target': '黑风寨', 'desc': '前往黑风寨', 'count': 1}], 'rewards': {'silver': 80, 'gold': 50, 'xp': 40}, 'repeatable': False}, {'id': 'side_002', 'name': '医师的草药', 'desc': '小医师阿青需要草药', 'level_req': 3, 'objectives': [{'type': 'talk', 'target': '小医师阿青', 'desc': '与小医师阿青交谈', 'count': 1}, {'type': 'visit', 'target': '温泉谷', 'desc': '前往温泉谷', 'count': 1}], 'rewards': {'silver': 60, 'gold': 80, 'xp': 50}, 'repeatable': True}, {'id': 'side_003', 'name': '武痴的挑战', 'desc': '武痴赵猛要与你切磋', 'level_req': 5, 'objectives': [{'type': 'talk', 'target': '武痴赵猛', 'desc': '与武痴赵猛交谈', 'count': 1}, {'type': 'practice', 'desc': '在擂台练习', 'count': 5}], 'rewards': {'silver': 150, 'gold': 100, 'xp': 100}, 'repeatable': True}, {'id': 'side_004', 'name': '秘籍之谜', 'desc': '武林秘籍库深夜有异响', 'level_req': 6, 'objectives': [{'type': 'talk', 'target': '看门老者', 'desc': '与看门老者交谈', 'count': 1}, {'type': 'visit', 'target': '武林秘籍库', 'desc': '前往武林秘籍库', 'count': 2}], 'rewards': {'silver': 100, 'gold': 200, 'xp': 150}, 'repeatable': False}, {'id': 'side_005', 'name': '老顽童的游戏', 'desc': '周伯通想找人玩游戏', 'level_req': 10, 'objectives': [{'type': 'talk', 'target': '周伯通', 'desc': '与周伯通交谈', 'count': 1}, {'type': 'visit', 'target': '温泉谷', 'desc': '前往温泉谷', 'count': 1}], 'rewards': {'silver': 200, 'gold': 300, 'xp': 200}, 'repeatable': True}]

DAILY_QUESTS = [{'id': 'daily_001', 'name': '每日练功', 'desc': '勤学苦练', 'objectives': [{'type': 'practice', 'desc': '练功', 'count': 1}], 'rewards': {'xp': 30, 'silver': 20}}, {'id': 'daily_002', 'name': '江湖行侠', 'desc': '见识各方人物', 'objectives': [{'type': 'talk', 'desc': '与NPC交谈', 'count': 2}], 'rewards': {'xp': 20, 'silver': 30}}, {'id': 'daily_003', 'name': '武斗大会', 'desc': '与高手切磋', 'objectives': [{'type': 'visit', 'target': '擂台', 'desc': '前往擂台', 'count': 1}], 'rewards': {'xp': 50, 'silver': 50, 'gold': 50}}]

ACHIEVEMENTS = [{'id': 'ach_001', 'name': '初出茅庐', 'desc': '完成第一次练功', 'condition': {'practice_count': 1}, 'rewards': {'xp': 10}}, {'id': 'ach_002', 'name': '江湖游侠', 'desc': '访问5个不同地点', 'condition': {'unique_locations': 5}, 'rewards': {'xp': 50, 'silver': 100}}, {'id': 'ach_003', 'name': '交友广泛', 'desc': '与5个NPC建立友好关系', 'condition': {'npc_relationships': 5}, 'rewards': {'xp': 80, 'gold': 200}}, {'id': 'ach_004', 'name': '武学突破', 'desc': '第一次突破境界', 'condition': {'breakthroughs': 1}, 'rewards': {'xp': 100, 'silver': 200}}, {'id': 'ach_005', 'name': '武林高手', 'desc': '达到三流高手', 'condition': {'realm_index': 1}, 'rewards': {'xp': 200, 'gold': 500}}, {'id': 'ach_006', 'name': '富甲一方', 'desc': '拥有1000银两', 'condition': {'silver': 1000}, 'rewards': {'xp': 150}}, {'id': 'ach_007', 'name': '剑指天下', 'desc': '达到一流高手', 'condition': {'realm_index': 3}, 'rewards': {'xp': 500, 'gold': 1000}}, {'id': 'ach_008', 'name': '一代宗师', 'desc': '达到宗师境界', 'condition': {'realm_index': 4}, 'rewards': {'xp': 1000, 'gold': 2000}}]
